### ISSUE TITLE
workflow should make "all" rather than "subset" by default

### ISSUE THREAD

**Issue by tonytony99** [SaundersLab/marple#9]
Options:
- `--config existing_samples=subset` vs `--config existing_samples=all` (default)
- `snakemake --use-conda -cores 2 results/pgt/trees/pgt_subset.pdf` (not ideal because only 1 organism and no multiqc)
- put it in a config file too?

Context:
- The subset will probably not be run in the workshops
- We almost always want the full tree in production
- We need the subset tree for tests and development

**Comment by 502107** [comment]
Tree now built against all isolates (can still use subset, but with fasttree we see a significant speedup and can probably just use that all the time)
